# Configuration file for run-L1-mock program.
#
# This file defines the configuration file format.


source:
    # Where the data come from.
    type: vdif
    # Where to get the vdif packets
    vdif_source:
        type: network
    # Another example of a vdif source
    # source:
    #     type: moose_acq
    #     moose_acq_name: 20151026T084446Z_chime_beamformed
    nframe_integrate: 24
    nchan_upsamp: 16

# Or a completely different source type.
# source:
#     type: from_disk
#     data_dir: path/to/data/


preprocess:
    # Parameters passed to data preprocessing.
    detrend: subtract_mean
    # Presence of this mapping triggers injection of simulated events.
    inject:
        rate: 0.001  # Hz
        # more parameters


dedisperse:
    # Parameters passed to the dedisperser (bonsai)

    # Note that the parameters nchan, freq_lo_MHz, freq_hi_MHz, and dt_sample
    # do not appear. These are provided by the data source.
    # nt_data too?

    nt_data: 1024
    # A list of mappings specifying each tree.
    trees:
        - nds: 1
          nt_tree: 512

        - nds: 2
          nt_tree: 256

    # Parameters that could be tree dependant but aren't may be specified
    # outside of *trees*
    tree_size: 4096
    nups: 1
    nsm: 1
    sm_depth: 1


postprocess:
    # Parameters passed to the sifter.
    threshold: 10


actions:
    # Specifies what action to take on trigger.
    # This is a list of mappings.
    - type: save_waterfall_plot
    - type: save_raw_data
    - type: send_header
      port: 20046
    - type: print_to_screen



