# Configuration file for run-L1-mock program.
#
# This file defines the configuration file format. It is a road-map,
# with no guarantee that any of these parameters are used or implemented.


# Global parameters

ntime_chunk: 1024

source:
    # Where the data come from.
    type: vdif
    # Where to get the vdif packets with parameters. Should support all
    # functionality of corr-vdif.
    vdif_source:
        type: network
    # Another example of a vdif source
    # source:
    #     type: moose_acq
    #     acq_name: 20151026T084446Z_chime_beamformed
    nframe_integrate: 24
    nchan_upsamp: 16

# Or a completely different source type.
# source:
#     type: disk
#     data_dir: path/to/data/

# Plan to have source types: vdif, from_disk, network


preprocess:
    # Parameters passed to data preprocessing.
    - type: thermal_noise_weight
    - type: subtract_mean
    - type: inject
      rate: 0.001  # Hz


dedisperse:
    # Parameters passed to the dedisperser (bonsai)

    # Note that the parameters nchan, freq_lo_MHz, freq_hi_MHz, and dt_sample
    # do not appear. These are provided by the data source.

    tree_size: 4096
    nthreads: 2
    nups: 1
    nsm: 1
    nbeta: 1
    ndm_per_trigger: 64
    nt_per_trigger: 64
    beta_min: 0.
    beta_max: 0.
    nds: [1, 2, 4]


postprocess:
    # Parameters passed to the sifter.
    threshold: 10


action:
    # Specifies what action to take on trigger.
    # This is a list of mappings.
    - type: save_waterfall_plot
    - type: save_raw_data
    - type: send_header
      port: 20046
    - type: print_to_stdout



